"""
api/ — FastAPI application package for WADA Compliance System

This package exposes the FastAPI `app` instance and its registered
routers so that both the uvicorn launcher and the test suite can
import from a single, consistent location.

──────────────────────────────────────────────────────────────────────
Registered endpoints
──────────────────────────────────────────────────────────────────────
  GET  /              → Service info + endpoint map
  GET  /health        → Cloud Run liveness probe  {"status": "ok"}
  POST /analyze-supplement
      Body : AnalyzeRequest  {input_type, data, athlete_sport?}
      Returns: AnalyzeResponse {risk_level, ingredients, flagged,
               confidence, explanation, athlete_advice, trace,
               wada_list_version, disclaimer}

  POST /analyze-batch
      Body : BatchAnalyzeRequest  {items: list[AnalyzeRequest]}
      Returns: BatchAnalyzeResponse {results: list[AnalyzeResponse]}
      Max batch size: 10 items (processed concurrently with asyncio.gather)

  GET  /docs          → Swagger UI  (auto-generated by FastAPI)
  GET  /redoc         → ReDoc UI    (auto-generated by FastAPI)

──────────────────────────────────────────────────────────────────────
Lifespan behaviour
──────────────────────────────────────────────────────────────────────
On startup the app pre-warms the WADA prohibited list cache by calling
fetch_wada_list_tool(). This reduces first-request latency on Cloud Run
cold starts. If the fetch fails the app still starts (non-fatal).

──────────────────────────────────────────────────────────────────────
Import paths
──────────────────────────────────────────────────────────────────────
    from api import app          # preferred — single symbol
    from api.app import app      # also works — direct module import

Uvicorn launch string (used in main.py):
    uvicorn.run("api.app:app", host="0.0.0.0", port=8080)
"""

from api.app import app

__all__ = ["app"]
